# Generated by Django 4.1.5 on 2023-01-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='winning_bid',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
