# Generated by Django 4.1.5 on 2023-01-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_active_comments_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='starting_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='winning_bid',
        ),
    ]
